#!/bin/sh
### BEGIN INIT INFO
# Provides:          wsddn
# Required-Start:    $network $local_fs 
# Required-Stop:     $network $local_fs 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: WS-Discovery Host Daemon
# Description:       Allows your Linux machine to be discovered by Windows 10 
#          and above systems and displayed by their 
#          Explorer "Network" views.
### END INIT INFO

NAME="wsddn"
DESC="WS-Discovery Host Daemon"
DAEMON="/usr/bin/$NAME"
SCRIPTNAME=/etc/init.d/$NAME
PIDFILE=/var/run/$NAME/$NAME.pid
LOGFILE=/var/log/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

. /lib/lsb/init-functions

NETWORK_JSON=$(jq '.' /boot/config/network.json 2>/dev/null)

case $1 in
  start)
    log_daemon_msg "Starting $DESC" $NAME
    HOSTNAME=$(jq -r '.hostname' /boot/config/system.json 2>/dev/null)
    BRIDGED=$(echo $NETWORK_JSON | jq -r '.interfaces[] | select(.name == "eth0") | .type')
    if [ "$BRIDGED" == "bridged" ] ; then
      INTERFACE_NAME="br0"
    else
      INTERFACE_NAME="eth0"
    fi
    
    IPV6=$(echo $NETWORK_JSON | jq -r '.interfaces | map(select((.type != "bridged") and (.ipv6 | length > 0))) | length > 0')
    if [ "${IPV6}" = "false" ] ; then
      IPV4ONLY="--ipv4only"
    else
      IPV4ONLY=""
    fi

    if ! start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- --unixd --pid-file=$PIDFILE --log-file=$LOGFILE --smb-conf /etc/samba/smb.conf --hostname "$HOSTNAME" --interface "$INTERFACE_NAME" $IPV4ONLY ; then
      log_end_msg 1
      exit 1
    fi

    log_end_msg 0
  ;;
  stop)

    log_daemon_msg "Stopping $DESC" $NAME

    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    # Wait a little and remove stale PID file in case it is left over
    sleep 1
    if [ -f $PIDFILE ] && ! ps h `cat $PIDFILE` > /dev/null
    then
      rm -f $PIDFILE
    fi

    log_end_msg 0

  ;;
  reload)
    log_daemon_msg "Reloading $DESC" $NAME

    start-stop-daemon --stop --quiet --signal HUP --pidfile $PIDFILE

    log_end_msg 0
  ;;
  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
  ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME
    exit $?
  ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|reload|restart|force-reload|status}"
    exit 1
  ;;
esac

exit 0
